---
- name: Install Jenkins
  apt:
    name: openjdk-11-jdk
    state: present
  become: true

- name: Add Jenkins repository
  apt_repository:
    repo: "deb http://pkg.jenkins.io/debian/ stable main"
    state: present
  become: true

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  become: true

- name: Start Jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes
  become: true
