version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    networks:
      - mental-health-net

  frontend:
    build: ./frontend
    ports:
      - "5003:5003"
    depends_on:
      - backend
    networks:
      - mental-health-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mental-health-net

networks:
  mental-health-net:
    driver: bridge