---
- name: Update apt package index
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name:
      - curl
      - wget
      - git
      - unzip
      - python3-pip
      - python3-dev
      - build-essential
      - libssl-dev
      - libffi-dev
    state: present

- name: Set timezone
  timezone:
    name: UTC

- name: Create deployment user
  user:
    name: deploy
    group: admin
    shell: /bin/bash
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Add deploy user to sudoers
  copy:
    dest: /etc/sudoers.d/deploy
    content: "deploy ALL=(ALL) NOPASSWD:ALL"
    validate: 'visudo -cf %s'