---
- name: Create project directory
  file:
    path: "{{ deploy_path }}"
    state: directory
    mode: '0755'

- name: Copy docker-compose.yml to deploy path
  copy:
    src: "{{ project_root }}/docker-compose.yml"
    dest: "{{ deploy_path }}/docker-compose.yml"

- name: Check for running containers with same names
  command: docker ps -a --filter "name=mental-health-" --format "{{ '{{.Names}}' }}"
  register: existing_containers
  changed_when: false
  ignore_errors: yes

- name: Show existing containers (debug)
  debug:
    var: existing_containers.stdout_lines
  when: existing_containers.stdout_lines | length > 0

- name: Stop and remove existing containers if found
  command: docker compose down
  args:
    chdir: "{{ deploy_path }}"
  when: existing_containers.stdout_lines | length > 0
  register: compose_down
  ignore_errors: yes

- name: Bring up services with Docker Compose
  command: docker compose up -d --build
  args:
    chdir: "{{ deploy_path }}"
  register: compose_up
  retries: 3
  delay: 5
  until: compose_up.rc == 0

- name: Verify services are running
  command: docker compose ps --services --filter "status=running"
  args:
    chdir: "{{ deploy_path }}"
  register: running_services
  changed_when: false

- name: Show running services
  debug:
    msg: "Running services: {{ running_services.stdout_lines }}"