---
# Database credentials
db_username: "{{ vault_db_username }}"
db_password: "{{ vault_db_password }}"

# API keys
api_key: "{{ vault_api_key }}"

# Docker Hub credentials
docker_hub_username: "{{ vault_docker_hub_username }}"
docker_hub_password: "{{ vault_docker_hub_password }}"