---
- name: Deploy Backend to Kubernetes
  command:
    cmd: kubectl apply -f /opt/mental-health/kubernetes/backend-deployment.yml --validate=false
  become: no

- name: Deploy Backend Service to Kubernetes
  command:
    cmd: kubectl apply -f /opt/mental-health/kubernetes/backend-service.yml
  become: no

- name: Deploy Frontend to Kubernetes
  command:
    cmd: kubectl apply -f /opt/mental-health/kubernetes/frontend-deployment.yml
  become: no

- name: Deploy Frontend Service to Kubernetes
  command:
    cmd: kubectl apply -f /opt/mental-health/kubernetes/frontend-service.yml
  become: no
