---
- name: Deploy Backend Deployment
  command: kubectl apply -f {{ project_root }}/kubernetes/backend-deployment.yml
  become: no

- name: Deploy Backend Service
  command: kubectl apply -f {{ project_root }}/kubernetes/backend-service.yml
  become: no

- name: Deploy Frontend Deployment
  command: kubectl apply -f {{ project_root }}/kubernetes/frontend-deployment.yml
  become: no

- name: Deploy Frontend Service
  command: kubectl apply -f {{ project_root }}/kubernetes/frontend-service.yml
  become: no
