---
- name: Install application dependencies
  apt:
    name: 
      - curl
      - git
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Ensure application target directory exists
  file:
    path: "{{ app_target }}"
    state: directory
    mode: '0755'

- name: Copy application code to localhost target directory
  copy:
    src: "{{ app_source }}/"
    dest: "{{ app_target }}/"
    mode: '0755'
  delegate_to: localhost

- name: Install Python requirements
  pip:
    requirements: "{{ app_target }}/backend/requirements.txt"

- name: Start backend service
  shell: "nohup python3 {{ app_target }}/backend/app.py &"
  args:
    chdir: "{{ app_target }}/backend/"
  async: 10
  poll: 0

- name: Start frontend service
  shell: "nohup python3 {{ app_target }}/frontend/app.py &"
  args:
    chdir: "{{ app_target }}/frontend/"
  async: 10
  poll: 0
