---
- name: Configure monitoring stack
  hosts: prod
  become: true
  tasks:
    - name: Ensure ELK directories exist
      file:
        path: "/etc/elk/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - elasticsearch
        - logstash
        - kibana
        - filebeat

    - name: Copy ELK configuration files
      copy:
        src: "../../{{ item.src }}"
        dest: "/etc/elk/{{ item.dest }}"
      loop:
        - { src: 'filebeat.yml', dest: 'filebeat/filebeat.yml' }
        - { src: 'logstash.conf', dest: 'logstash/logstash.conf' }

    - name: Start ELK services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - elasticsearch
        - logstash
        - kibana
        - filebeat