---
- name: Deploy application to production
  hosts: prod
  become: true
  vars_files:
    - ../vars/secrets.yml
  tasks:
    - name: Ensure deployment directory exists
      file:
        path: /opt/mental_health
        state: directory
        mode: '0755'
      
    - name: Copy application files
      copy:
        src: "../../"
        dest: /opt/mental_health
        remote_src: no

    - name: Deploy using docker-compose
      community.docker.docker_compose:
        project_src: /opt/mental_health
        files:
          - docker-compose.yml
        state: present
        recreate: always
        pull: yes