---
- name: Create backend directory
  file:
    path: "{{ deploy_path }}/backend"
    state: directory
    mode: '0755'

- name: Copy backend files
  copy:
    src: "{{ project_root }}/backend"
    dest: "{{ deploy_path }}"
    remote_src: no
