---
- name: Add Elasticsearch GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    filename: elastic-7.x

- name: Install ELK stack
  apt:
    name:
      - elasticsearch
      - logstash
      - kibana
      - filebeat
    state: present
    update_cache: yes

- name: Configure Elasticsearch
  template:
    src: templates/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '0640'
  notify: restart elasticsearch

- name: Configure Logstash
  template:
    src: templates/logstash.conf.j2
    dest: /etc/logstash/conf.d/logstash.conf
    owner: root
    group: logstash
    mode: '0640'
  notify: restart logstash

- name: Configure Kibana
  template:
    src: templates/kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: '0640'
  notify: restart kibana

- name: Configure Filebeat
  template:
    src: templates/filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0640'
  notify: restart filebeat

- name: Start and enable ELK services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - elasticsearch
    - logstash
    - kibana
    - filebeat