---
- name: Run all roles for MLOps project on localhost
  hosts: localhost
  become: true
  vars:
    app_source: "/home/naman/Desktop/MLOpsSPE"  # base path to your full project
    app_target: "/home/naman/Desktop/app"               # where it will be copied and run
    backend_file: "backend/app.py"
    frontend_file: "frontend/app.py"
    backend_port: 5001
    frontend_port: 5003

  roles:
    - docker
    - jenkins
    - app_deploy
