- name: Deploy Mental Health Prediction App
  hosts: k8s-master
  become: yes

  tasks:
    - name: Apply Kubernetes Configurations
      shell: kubectl apply -f /home/naman/Desktop/MLOpsSPE/kubernetes
